clean up

diff --git a/.github/workflows/peertube.yml b/.github/workflows/peertube.yml
--- a/.github/workflows/peertube.yml
+++ b/.github/workflows/peertube.yml
@@ -58,54 +58,54 @@ jobs:
           docker build . --file $DOCKER_FILE --tag $DOCKER_REPOSITORY/${{ github.repository_owner }}/$DOCKER_IMAGE:$IMAGE_TAG --build-arg POSTGRES_PASSWORD=$POSTGRES_PASSWORD --build-org PEERTUBE_SECRET=$PEERTUBE_SECRET
           docker push -a $DOCKER_REPOSITORY/${{ github.repository_owner }}/$DOCKER_IMAGE
 
-  deploy_image:
-    needs: [push_images]
+  # deploy_image:
+  #   needs: [push_images]
 
-    runs-on: ubuntu-latest
+  #   runs-on: ubuntu-latest
 
-    env:
-      IMAGE_TAG: ${{ github.ref_name }}
-      DOCKER_REPOSITORY: ghcr.io
+  #   env:
+  #     IMAGE_TAG: ${{ github.ref_name }}
+  #     DOCKER_REPOSITORY: ghcr.io
 
-    strategy:
-      matrix:
-        app: [ellandi-api, organogram, ellandi, ellandi-recommender]
+  #   strategy:
+  #     matrix:
+  #       app: [peertube]
 
-    steps:
-      - uses: actions/checkout@v3
+  #   steps:
+  #     - uses: actions/checkout@v3
 
-      - name: Get non-prod space name
-        if:  ${{ github.event_name != 'release' }}
-        uses: kanga333/variable-mapper@v0.2.2
-        with:
-          key: "${{github.ref_name}}"
-          map: |
-            {
-              "sandbox": {"CF_SPACE": "sandbox"},
-              "demo": {"CF_SPACE": "demo"},
-              "temp": {"CF_SPACE": "temp"},
-              "develop": {"CF_SPACE": "develop"},
-              "staging": {"CF_SPACE": "staging"},
-              "pentest": {"CF_SPACE": "pentest"},
-              "feature/deploy-from-main": {"CF_SPACE": "flibble"}
-            }
+  #     - name: Get non-prod space name
+  #       if:  ${{ github.event_name != 'release' }}
+  #       uses: kanga333/variable-mapper@v0.2.2
+  #       with:
+  #         key: "${{github.ref_name}}"
+  #         map: |
+  #           {
+  #             "sandbox": {"CF_SPACE": "sandbox"},
+  #             "demo": {"CF_SPACE": "demo"},
+  #             "temp": {"CF_SPACE": "temp"},
+  #             "develop": {"CF_SPACE": "develop"},
+  #             "staging": {"CF_SPACE": "staging"},
+  #             "pentest": {"CF_SPACE": "pentest"},
+  #             "feature/deploy-from-main": {"CF_SPACE": "flibble"}
+  #           }
 
-      - name: Get prod space name
-        if:  ${{ github.event_name == 'release' }}
-        uses: kanga333/variable-mapper@v0.2.2
-        with:
-          key: "${{github.ref_name}}"
-          map: |
-            {
-              "v?.?.?": {"CF_SPACE": "prod"},
-              "feature/deploy-from-main": {"CF_SPACE": "flibble"}
-            }
+  #     - name: Get prod space name
+  #       if:  ${{ github.event_name == 'release' }}
+  #       uses: kanga333/variable-mapper@v0.2.2
+  #       with:
+  #         key: "${{github.ref_name}}"
+  #         map: |
+  #           {
+  #             "v?.?.?": {"CF_SPACE": "prod"},
+  #             "feature/deploy-from-main": {"CF_SPACE": "flibble"}
+  #           }
 
-      - name: Download CF CLI
-        run: curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&version=v7&source=github" | tar -zx
+  #     - name: Download CF CLI
+  #       run: curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&version=v7&source=github" | tar -zx
 
-      - name: CF login
-        run: ./cf login -a api.london.cloud.service.gov.uk -u "${{ secrets.CF_USER }}" -p "${{ secrets.CF_PASSWORD }}" -o co-i-ai -s "$CF_SPACE"
+  #     - name: CF login
+  #       run: ./cf login -a api.london.cloud.service.gov.uk -u "${{ secrets.CF_USER }}" -p "${{ secrets.CF_PASSWORD }}" -o co-i-ai -s "$CF_SPACE"
 
       - name: CF push ${{ matrix.app }}
         if:  ${{ matrix.app != 'ellandi-recommender' }}
@@ -126,15 +126,15 @@ jobs:
         run: CF_DOCKER_PASSWORD="$PAT_TOKEN" ./cf push -f manifests/"$CF_SPACE/${{ matrix.app }}"_manifest.yml --docker-image $DOCKER_REPOSITORY/${{ github.repository_owner }}/$DOCKER_IMAGE:$IMAGE_TAG --docker-username=$PAT_TOKEN_USER --no-start
 
 
-      - uses: actions/checkout@v2
-      - name: Slack Notification
-        continue-on-error: true
-        if: ${{ failure() && github.ref_name == 'prod' || failure() && github.ref_name == 'develop' }}
-        uses: rtCamp/action-slack-notify@v2
-        env:
-          SLACK_COLOR: '#FF0000'
-          SLACK_ICON: https://avatars0.githubusercontent.com/u/818058?s=200&v=4
-          SLACK_TITLE: '${{ github.ref_name }} deployment ${{ job.status }} :warning:'
-          SLACK_USERNAME: ${{ github.actor }}
-          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
-          SLACK_MESSAGE: '${{ github.ref_name }} Action ${{ job.status }}'
+  #     - uses: actions/checkout@v2
+  #     - name: Slack Notification
+  #       continue-on-error: true
+  #       if: ${{ failure() && github.ref_name == 'prod' || failure() && github.ref_name == 'develop' }}
+  #       uses: rtCamp/action-slack-notify@v2
+  #       env:
+  #         SLACK_COLOR: '#FF0000'
+  #         SLACK_ICON: https://avatars0.githubusercontent.com/u/818058?s=200&v=4
+  #         SLACK_TITLE: '${{ github.ref_name }} deployment ${{ job.status }} :warning:'
+  #         SLACK_USERNAME: ${{ github.actor }}
+  #         SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
+  #         SLACK_MESSAGE: '${{ github.ref_name }} Action ${{ job.status }}'
